/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SitemapDotxmlRouteImport } from './pages/sitemap[.]xml'
import { Route as SaradRouteImport } from './pages/sarad'
import { Route as ProductsRouteImport } from './pages/products'
import { Route as PortfolioRouteImport } from './pages/portfolio'
import { Route as MarketingRouteImport } from './pages/marketing'
import { Route as HrConsultancyRouteImport } from './pages/hr-consultancy'
import { Route as EcommerceRouteImport } from './pages/ecommerce'
import { Route as ContactRouteImport } from './pages/contact'
import { Route as BlogRouteImport } from './pages/blog'
import { Route as AboutRouteImport } from './pages/about'
import { Route as IndexRouteImport } from './pages/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SaradRoute = SaradRouteImport.update({
  id: '/sarad',
  path: '/sarad',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HrConsultancyRoute = HrConsultancyRouteImport.update({
  id: '/hr-consultancy',
  path: '/hr-consultancy',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/ecommerce': typeof EcommerceRoute
  '/hr-consultancy': typeof HrConsultancyRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/sarad': typeof SaradRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/ecommerce': typeof EcommerceRoute
  '/hr-consultancy': typeof HrConsultancyRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/sarad': typeof SaradRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/ecommerce': typeof EcommerceRoute
  '/hr-consultancy': typeof HrConsultancyRoute
  '/marketing': typeof MarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/products': typeof ProductsRoute
  '/sarad': typeof SaradRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/ecommerce'
    | '/hr-consultancy'
    | '/marketing'
    | '/portfolio'
    | '/products'
    | '/sarad'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/ecommerce'
    | '/hr-consultancy'
    | '/marketing'
    | '/portfolio'
    | '/products'
    | '/sarad'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/ecommerce'
    | '/hr-consultancy'
    | '/marketing'
    | '/portfolio'
    | '/products'
    | '/sarad'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  EcommerceRoute: typeof EcommerceRoute
  HrConsultancyRoute: typeof HrConsultancyRoute
  MarketingRoute: typeof MarketingRoute
  PortfolioRoute: typeof PortfolioRoute
  ProductsRoute: typeof ProductsRoute
  SaradRoute: typeof SaradRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarad': {
      id: '/sarad'
      path: '/sarad'
      fullPath: '/sarad'
      preLoaderRoute: typeof SaradRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-consultancy': {
      id: '/hr-consultancy'
      path: '/hr-consultancy'
      fullPath: '/hr-consultancy'
      preLoaderRoute: typeof HrConsultancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  EcommerceRoute: EcommerceRoute,
  HrConsultancyRoute: HrConsultancyRoute,
  MarketingRoute: MarketingRoute,
  PortfolioRoute: PortfolioRoute,
  ProductsRoute: ProductsRoute,
  SaradRoute: SaradRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
